service: restbucks-lambda-home

provider:
  name: aws
  runtime: nodejs12.x

functions:
  homeHandler:
    handler: src/homeHandler.handler
    events:
      - http:
          method: get
          path: home
